# .readthedocs.yaml -*- mode: YAML -*-
# https://blog.readthedocs.com/migrate-configuration-v2/
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

sphinx:
  configuration: acab/_docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_create_environment:
      - mkdir -p .temp/egg-info
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv lock --no-sources
      - uv venv --refresh "READTHEDOCS_VIRTUALENV_PATH"
    install:
      - UV_PROJECT_ENVIRONMENT="READTHEDOCS_VIRTUALENV_PATH" uv sync --frozen --group docs 
    build:
      html:
        - echo "Building HTML"
        - mkdir -p $READTHEDOCS_OUTPUT/html
        - >
          UV_PROJECT_ENVIRONMENT="READTHEDOCS_VIRTUALENV_PATH"
          OUTDIR="READTHEDOCS_OUTPUT/html/"
          DOCTREE="_build/doctrees"
          uv run --frozen
          tox -e docs
