from acab.abstract.config.config import GET

config = GET()

ACTION         : str = config.value("Parse.Structure", "ACTION")
ANNOTATION     : str = config.value("Parse.Structure", "ANNOTATION")
ARG            : str = config.value("Parse.Structure", "PARAMS")
AT_BIND        : str = config.value("Parse.Structure", "AT_BIND")
BIND           : str = config.value("Parse.Structure", "BIND")
CONSTRAINT     : str = config.value("Parse.Structure", "CONSTRAINT")
DEFAULT_ACTION : str = config.value("Parse.Structure", "DEFAULT_ACTION")
LEFT           : str = config.value("Parse.Structure", "LEFT")
MODAL          : str = config.value("Parse.Structure", "MODAL")
NAME           : str = config.value("Parse.Structure", "NAME")
NEGATION       : str = config.value("Parse.Structure", "NEGATION")
NODE           : str = config.value("Parse.Structure", "NODE")
OPERATOR       : str = config.value("Parse.Structure", "OPERATOR")
QUERY_FALLBACK : str = config.value("Parse.Structure", "QUERY_FALLBACK")
QUERY          : str = config.value("Parse.Structure", "QUERY")
RIGHT          : str = config.value("Parse.Structure", "RIGHT")
SEN            : str = config.value("Parse.Structure", "SEN")
STATEMENT      : str = config.value("Parse.Structure", "STATEMENT")
TAG            : str = config.value("Parse.Structure", "TAG")
TARGET         : str = config.value("Parse.Structure", "TARGET")
TRANSFORM      : str = config.value("Parse.Structure", "TRANSFORM")
TYPE_INSTANCE  : str = config.value("Parse.Structure", "TYPE_INSTANCE")
VALUE          : str = config.value("Parse.Structure", "VALUE")
