[default]
# Note: Use configparser.ConfigParser(interpolation=configparser.ExtendedInterpolation(), allow_no_value=True)
## Misc settings that don't fit elsewhere

[logging]
# Control detailed logging elements here
# If True, use acab_config.utils.log_formatter
# else just install the AcabMinimalLogRecord
ACAB          = True

STREAM_FORMAT = "{levelname:10} : {message}"
FILE_FORMAT   = "{levelname:10} : {shortname} : {message}"

# Overriden by CLI for the repl, otherwise:
STREAM_LEVEL  = "WARNING"
FILE_LEVEL    = "DEBUG"
# Separate file level semantic trace
SEMANTIC      = "WARNING"
# If True, attach a warning log to node and value destructors:
DEL           = false
# Use the 'rich' module's exception printing:
rich_exceptions = true

[handler.system]
DEFAULT_SIGNAL = "_default"

[imports]
# Target Name to try to import when importing a module
# before falling back to __init__
# ie: import a.b.c -> a.b.c.{target}
# See module_loader
MODULE_TARGET = "module"

[imports.targeted]
# Specific classes to use accessed through config,
# Rather than the parse/semantic/print AcabModules
# use config.actions_e.IMCLASS to import,
# and pass an interface/protocol it has to match in args={'interface': {}}
value_meta = "acab.core.metaclasses.value.ValueMeta"
# value_meta = acab.modules.values.string_cache_val.caching_meta.StringCacheValueMeta
bind       = "acab.modules.values.binding.binding.Bind"
context    = "acab.modules.context.context_set.ContextSet"
debug      = "acab.modules.debugger.running_debugger.RunningDebugger"
engine     = "acab.modules.engines.basic_engine.AcabBasicEngine"
handler    = 'acab.core.util.patch_handler.PatchHandler'

[data]
# The base root name in a data structure:
ROOT                  = "__root"
# The Base Type:
TYPE_BASE             = "ATOM"
DEFAULT_SETUP_METHOD  = "_default_setup"
DEFAULT_UPDATE_METHOD = "_update_node"

[[types]]
# Names to be turned into the base type sentences
# on top of TYPE_BASE
primitives = ["ACTION", "COMPONENT", "CONTAINER", "INSTRUCT", "OPERATOR_PRIM", "QUERY", "REGEX", "RULE", "SENTENCE", "STRING", "STRUCTURE", "TRANSFORM"]
structures = ["TRANSFORM", "QUERY", "ACTION"]

[[values]]
# These are used in AcabValue.data
# to add metadata
structure = ["ARG", "AT_BIND", "BIND", "CONSTRAINT", "NAME", "NEGATION", "OPERATOR", "PARAMS", "QUERY", "QUERY_FALLBACK", "SEN", "TAG", "TYPE_INSTANCE", "SEMANTIC_HINT", "FLATTEN"]

[[symbols]]
# For Parsing / Printing
[[aliases]]
# Alias with [Semantic.Signals] to provide easier ways of
# specifying statement types
[[modal]]
# Modalities to load.
# DONT FORGET: KEYS ARE STORED *lowercase* in configparsers
# will insist there is a [Modal.{}] section
# and [Modal.{}.Symbols] section for each name
# [Modal.{}] specifies ENUM_VALUES and DEFAULT
# [Modal.{}.Symbols] specifies the enum_val : parse symbol pairings
[[print]]
# Signals used for sub-printers, below the level of statements/atoms
[[parse]]
# Signals used for DSL component creation
[[semantic]]
# Signals used for assembling semantic components together

[[operators]]

[operators.sugar]
# Default pairings of operators to simpler sugar for use
# eg: !! a.b.c instead of λacab.modules.operators.actions.assert a.b.c
ASSERT          = "!!"
PRINT           = "%"
REBIND          = "§"
EQ              = "=="
NEQ             = "!="
REGEX_MATCH     = "~="
ELEM            = "∈"
TYPEMATCH       = "τ="
REGEX_TRANSFORM = "~:"
FORMAT          = "%:"
DFS             = "ᛦ"
